FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Configuración dinámica de Nginx usando la variable PORT
RUN apk add --no-cache envsubst
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 10000
CMD ["nginx", "-g", "daemon off;"]